### ISSUE TITLE
Group Milestone - Implementation (Sprint 1) complete

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/WomenWhoCode#60]
We completed the following: 
* [X] Finalize the app scope; separating your features into required, optional and bonus.
* [X] Divide up work for each team member to complete for this week into issues on Github assigned to a milestone.
* [X] Review the collaboration guide when starting your project.
* [X] Setup and configure Parse (or similar) server-side data store
* [X] Design your database schema and generated model objects with initial fields
* [X] Create the basics activities and fragments needed for developing early functionality.
* [X] Goal: Implement 50% or more of the functionality for your app

Our sprint milestone is here: https://github.com/WomenWhoCode/WomenWhoCode/milestones/Sprint%201

The readme is updated with gif for initial demo.

fyi @RoyPuja @shehbashahab 

/cc @codepathreview @codepath

**Comment by zassmin** [comment]
![initial_demo_wwcodeapp](https://cloud.githubusercontent.com/assets/1654151/10651410/2f133e8a-7804-11e5-9873-24271bd21fc3.gif)

**Comment by codepathreview** [comment]
:+1:  Excellent job guys, great to see all the wireframes and basic functionality of the app coming along so well and smooth!! Few notes to mention:

* Well created detailed stories/tasks.
* Nice way of splitting a parent task into a number of smaller subtasks - provides a better picture of the progress on the issue.
* Good job by everyone to [contribute] (https://github.com/WomenWhoCode/WomenWhoCode/graphs/contributors) to the project.  
* Impressed that you are already thinking about documenting overall strategy and most design decisions.
* Good to see that your team created regular commits to sync up your code to avoid having multiple conflicts at the end.
* Consider creating tasks to QA the app a few times to check the basic flow. Integration testing will especially be important for this project since each team member is working on a separate module. The best part is seeing it all come together into a polished app.

Good to see the basic flow coming along well. Please take notes of these points and improve upon the same in the next sprint. Look forward to the rest of the functionality and improvement on the core flows by the end of the Sprint 2 so you can have enough time to add UI polish and advanced nice-to-have features later on. It is those little extra things you do that make everything feel more polished and desirable to use.
